channels:
  - defaults
dependencies:
  - numpy>=1.20
  - pip>=20.3.3
  - python=3.9
  - pip:
      - matplotlib>=3.3.3
      - astropy==4.2.1
      - astroquery==0.4.3
      - corner==2.2.1
      - emcee==3.1.1
      - fastparquet>=0.7.1
      - matplotlib-label-lines
      - pandas==1.3.2
      - pyarrow>=5.0.0
      - seaborn==0.11.1
      - scipy>=1.6.2
      - tqdm==4.59.0
      